- hosts: all  # Replace with the correct group of AMP agent hosts
  tasks:
    # 1. Update apt cache
    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes
        lock_timeout: 120

    # 2. Upgrade ampinstmgr
    - name: Upgrade ampinstmgr to the latest version
      become: yes   
      apt:
        name: ampinstmgr
        state: latest
        lock_timeout: 120

    
    # 2. Upgrade amp instances
    - name: Upgrade AMP Instances to the latest version
      command: ampinstmgr upgradeall --nocache
      become_user: amp
  