- hosts: all  # Replace with the correct group of AMP agent hosts
  become_method: sudo
  become: true
  tasks:
    # 1. Update apt cache
    - name: Update apt cache
      apt:
        update_cache: yes
        lock_timeout: 120

    # 2. Upgrade ampinstmgr
    - name: Upgrade ampinstmgr to the latest version
      apt:
        name: ampinstmgr
        state: latest
        lock_timeout: 120

    
    # 2. Upgrade amp instances
    - name: Upgrade AMP Instances to the latest version
      command: ampinstmgr upgradeall --nocache
      become: true
      become_method: su
      become_user: amp
      become_flags: '-l'